import {
  collection,
  doc,
  addDoc,
  getDoc,
  getDocs,
  setDoc,
  updateDoc,
  deleteDoc,
  query,
  where,
  Query,
  DocumentData,
  WriteBatch,
  writeBatch,
} from 'firebase/firestore';
import { db } from '../lib/firebase';

/**
 * Generic function to get a single document by ID
 */
export const getDocument = async <T extends DocumentData>(
  collectionName: string,
  docId: string
): Promise<T | null> => {
  try {
    const docRef = doc(db, collectionName, docId);
    const docSnap = await getDoc(docRef);
    return docSnap.exists() ? (docSnap.data() as T) : null;
  } catch (error) {
    console.error(`Error fetching document from ${collectionName}:`, error);
    throw error;
  }
};

/**
 * Generic function to get all documents from a collection
 */
export const getCollection = async <T extends DocumentData>(
  collectionName: string
): Promise<T[]> => {
  try {
    const collectionRef = collection(db, collectionName);
    const querySnapshot = await getDocs(collectionRef);
    return querySnapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id } as unknown as T));
  } catch (error) {
    console.error(`Error fetching collection ${collectionName}:`, error);
    throw error;
  }
};

/**
 * Generic function to query documents with conditions
 */
export const queryCollection = async <T extends DocumentData>(
  collectionName: string,
  conditions: Array<[string, string, any]>
): Promise<T[]> => {
  try {
    const collectionRef = collection(db, collectionName);
    let q: Query<DocumentData> = collectionRef as Query<DocumentData>;

    if (conditions.length > 0) {
      const whereConditions = conditions.map(([field, operator, value]) =>
        where(field, operator as any, value)
      );
      q = query(collectionRef, ...whereConditions);
    }

    const querySnapshot = await getDocs(q);
    return querySnapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id } as unknown as T));
  } catch (error) {
    console.error(`Error querying collection ${collectionName}:`, error);
    throw error;
  }
};

/**
 * Add or update a document
 */
export const setDocument = async <T extends DocumentData>(
  collectionName: string,
  docId: string,
  data: T,
  merge = true
): Promise<void> => {
  try {
    const docRef = doc(db, collectionName, docId);
    await setDoc(docRef, data, { merge });
  } catch (error) {
    console.error(`Error setting document in ${collectionName}:`, error);
    throw error;
  }
};

/**
 * Update specific fields in a document
 */
export const updateDocument = async <T extends Partial<DocumentData>>(
  collectionName: string,
  docId: string,
  data: T
): Promise<void> => {
  try {
    const docRef = doc(db, collectionName, docId);
    await updateDoc(docRef, data);
  } catch (error) {
    console.error(`Error updating document in ${collectionName}:`, error);
    throw error;
  }
};

/**
 * Delete a document
 */
export const deleteDocument = async (
  collectionName: string,
  docId: string
): Promise<void> => {
  try {
    const docRef = doc(db, collectionName, docId);
    await deleteDoc(docRef);
  } catch (error) {
    console.error(`Error deleting document from ${collectionName}:`, error);
    throw error;
  }
};

/**
 * Add a new document with autogenerated ID
 */
export const addDocument = async <T extends DocumentData>(
  collectionName: string,
  data: T
): Promise<string> => {
  try {
    const collectionRef = collection(db, collectionName);
    const docRef = await addDoc(collectionRef, data);
    return docRef.id;
  } catch (error) {
    console.error(`Error adding document to ${collectionName}:`, error);
    throw error;
  }
};

/**
 * Batch write operations
 */
export const batchWrite = async (
  operations: Array<{
    type: 'set' | 'update' | 'delete';
    collection: string;
    docId: string;
    data?: DocumentData;
  }>
): Promise<void> => {
  try {
    const batch: WriteBatch = writeBatch(db);

    for (const op of operations) {
      const docRef = doc(db, op.collection, op.docId);

      if (op.type === 'set') {
        batch.set(docRef, op.data || {});
      } else if (op.type === 'update') {
        batch.update(docRef, op.data || {});
      } else if (op.type === 'delete') {
        batch.delete(docRef);
      }
    }

    await batch.commit();
  } catch (error) {
    console.error('Error in batch write:', error);
    throw error;
  }
};

// Specific collection operations

/**
 * Student-specific operations
 */
export const studentDB = {
  getStudent: (studentId: string) =>
    getDocument(
      'students',
      studentId
    ),
  getAllStudents: () => getCollection('students'),
  addStudent: (data: any) => addDocument('students', data),
  updateStudent: (studentId: string, data: any) =>
    updateDocument('students', studentId, data),
  deleteStudent: (studentId: string) => deleteDocument('students', studentId),
};

/**
 * Faculty-specific operations
 */
export const facultyDB = {
  getFaculty: (facultyId: string) => getDocument('faculty', facultyId),
  getAllFaculty: () => getCollection('faculty'),
  addFaculty: (data: any) => addDocument('faculty', data),
  updateFaculty: (facultyId: string, data: any) =>
    updateDocument('faculty', facultyId, data),
  deleteFaculty: (facultyId: string) => deleteDocument('faculty', facultyId),
};

/**
 * Admin-specific operations
 */
export const adminDB = {
  getAdmin: (adminId: string) => getDocument('admins', adminId),
  getAllAdmins: () => getCollection('admins'),
  updateAdmin: (adminId: string, data: any) =>
    updateDocument('admins', adminId, data),
  deleteAdmin: (adminId: string) => deleteDocument('admins', adminId),
};

/**
 * Courses operations
 */
export const coursesDB = {
  getCourse: (courseId: string) => getDocument('courses', courseId),
  getAllCourses: () => getCollection('courses'),
  addCourse: (data: any) => addDocument('courses', data),
  updateCourse: (courseId: string, data: any) =>
    updateDocument('courses', courseId, data),
  deleteCourse: (courseId: string) => deleteDocument('courses', courseId),
};

/**
 * Grades operations
 */
export const gradesDB = {
  getGrade: (gradeId: string) => getDocument('grades', gradeId),
  getStudentGrades: (studentId: string) =>
    queryCollection('grades', [['studentId', '==', studentId]]),
  getAllGrades: () => getCollection('grades'),
  updateGrade: (gradeId: string, data: any) =>
    updateDocument('grades', gradeId, data),
  deleteGrade: (gradeId: string) => deleteDocument('grades', gradeId),
};

/**
 * Events operations
 */
export const eventsDB = {
  getEvent: (eventId: string) => getDocument('events', eventId),
  getAllEvents: () => getCollection('events'),
  addEvent: (data: any) => addDocument('events', data),
  updateEvent: (eventId: string, data: any) =>
    updateDocument('events', eventId, data),
  deleteEvent: (eventId: string) => deleteDocument('events', eventId),
};

/**
 * Announcements operations
 */
export const researchDB = {
  getResearch: (researchId: string) => getDocument('research', researchId),
  getAllResearch: () => getCollection('research'),
  addResearch: (data: any) => addDocument('research', data),
  updateResearch: (researchId: string, data: any) => updateDocument('research', researchId, data),
  deleteResearch: (researchId: string) => deleteDocument('research', researchId),
};

export const announcementsDB = {
  getAnnouncement: (announcementId: string) =>
    getDocument('announcements', announcementId),
  getAllAnnouncements: () => getCollection('announcements'),
  addAnnouncement: (data: any) => addDocument('announcements', data),
  updateAnnouncement: (announcementId: string, data: any) =>
    updateDocument('announcements', announcementId, data),
  deleteAnnouncement: (announcementId: string) =>
    deleteDocument('announcements', announcementId),
};